# Generated by Django 6.0 on 2025-12-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Diaries',
        ),
    ]
